version: 2
jobs:
  build_binary:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make build
            mkdir artifacts
            mv miniflux-* artifacts/
      - store_artifacts:
          path: artifacts/

workflows:
  version: 2
  build_all:
    jobs:
      - build_binary
